### ISSUE TITLE
Can't add crosstrainer, Don't even get logs.

### ISSUE THREAD

**Issue by LayerCakeMakes** [dudanov/hassio-ftms#28]
I'm trying to add my Crosstrainer to home assistant using the FTMS integration but I can't figure out if my Crosstrainer is just not supported or if the integration isn't running at all.
I've installed it through HACS and I've added the following to configuration.yaml but I see nothing in the logs at all.

```yaml
logger:
  logs:
    custom_components.ftms: debug
```
