### ISSUE TITLE
Feature request: Statistics!

### ISSUE THREAD

**Issue by quack3d** [dudanov/hassio-ftms#5]
So all the sensors start at 0 at the beginning of a session which is good. But I think it would be nice to have a few additional sensors that don't reset. For instance Distance total, Energy total, Step count and Time elapsed. Then we could make graphs showing how many steps etc every day for the last week. Or the distance walked/ran the last month. What thinks? 😊

**Comment by dudanov** [comment]
For this purposes you may use [`statistics`](https://www.home-assistant.io/integrations/statistics) integration sensors. For example:

```yaml
sensor:
  - platform: statistics
    name: Treadmill Daily Distance
    entity_id: sensor.treadmill_distance_total
    state_characteristic: sum_differences_nonnegative
    max_age:
      hours: 24
  - platform: statistics
    name: Treadmill Daily Energy
    entity_id: sensor.treadmill_energy_total
    state_characteristic: sum_differences_nonnegative
    max_age:
      hours: 24
  - platform: statistics
    name: Treadmill Daily Steps
    entity_id: sensor.treadmill_step_count
    state_characteristic: sum_differences_nonnegative
    max_age:
      hours: 24
  - platform: statistics
    name: Treadmill Daily Time
    entity_id: sensor.treadmill_time_elapsed
    state_characteristic: sum_differences_nonnegative
    max_age:
      hours: 24
```
